// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDeleteOwner = `-- name: AdminDeleteOwner :exec
DELETE FROM venue_owners
WHERE owner_uuid = $1
`

func (q *Queries) AdminDeleteOwner(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteOwner, ownerUuid)
	return err
}

const getOwnerDetails = `-- name: GetOwnerDetails :one
SELECT 
    owner_uuid, name, email, is_admin, is_demo, venue_limit, created_at, modified_at, mobile
FROM venue_owners
WHERE owner_uuid = $1
`

type GetOwnerDetailsRow struct {
	OwnerUuid  pgtype.UUID        `json:"owner_uuid"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	IsAdmin    bool               `json:"is_admin"`
	IsDemo     bool               `json:"is_demo"`
	VenueLimit int32              `json:"venue_limit"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	Mobile     string             `json:"mobile"`
}

func (q *Queries) GetOwnerDetails(ctx context.Context, ownerUuid pgtype.UUID) (GetOwnerDetailsRow, error) {
	row := q.db.QueryRow(ctx, getOwnerDetails, ownerUuid)
	var i GetOwnerDetailsRow
	err := row.Scan(
		&i.OwnerUuid,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.IsDemo,
		&i.VenueLimit,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Mobile,
	)
	return i, err
}

const listAllVenues = `-- name: ListAllVenues :many
SELECT 
    v.venue_uuid, 
    v.name, 
    v.address, 
    v.owner_uuid,
    o.name AS owner_name,
    o.email AS owner_email
FROM venues v
JOIN venue_owners o ON v.owner_uuid = o.owner_uuid
ORDER BY v.created_at DESC
`

type ListAllVenuesRow struct {
	VenueUuid  pgtype.UUID `json:"venue_uuid"`
	Name       string      `json:"name"`
	Address    string      `json:"address"`
	OwnerUuid  pgtype.UUID `json:"owner_uuid"`
	OwnerName  string      `json:"owner_name"`
	OwnerEmail string      `json:"owner_email"`
}

func (q *Queries) ListAllVenues(ctx context.Context) ([]ListAllVenuesRow, error) {
	rows, err := q.db.Query(ctx, listAllVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllVenuesRow{}
	for rows.Next() {
		var i ListAllVenuesRow
		if err := rows.Scan(
			&i.VenueUuid,
			&i.Name,
			&i.Address,
			&i.OwnerUuid,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetailsAllOwners = `-- name: ListDetailsAllOwners :many
SELECT 
    o.owner_uuid, 
    o.name, 
    o.email, 
    o.is_admin, 
    o.is_demo, 
    o.venue_limit,
    o.created_at,
    (SELECT COUNT(*) FROM venues v WHERE v.owner_uuid = o.owner_uuid) AS venue_count
FROM venue_owners o
ORDER BY o.created_at DESC
`

type ListDetailsAllOwnersRow struct {
	OwnerUuid  pgtype.UUID        `json:"owner_uuid"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	IsAdmin    bool               `json:"is_admin"`
	IsDemo     bool               `json:"is_demo"`
	VenueLimit int32              `json:"venue_limit"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	VenueCount int64              `json:"venue_count"`
}

func (q *Queries) ListDetailsAllOwners(ctx context.Context) ([]ListDetailsAllOwnersRow, error) {
	rows, err := q.db.Query(ctx, listDetailsAllOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetailsAllOwnersRow{}
	for rows.Next() {
		var i ListDetailsAllOwnersRow
		if err := rows.Scan(
			&i.OwnerUuid,
			&i.Name,
			&i.Email,
			&i.IsAdmin,
			&i.IsDemo,
			&i.VenueLimit,
			&i.CreatedAt,
			&i.VenueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOwnerAdmin = `-- name: SetOwnerAdmin :exec
UPDATE venue_owners
SET is_admin = $2
WHERE owner_uuid = $1
`

type SetOwnerAdminParams struct {
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
	IsAdmin   bool        `json:"is_admin"`
}

func (q *Queries) SetOwnerAdmin(ctx context.Context, arg SetOwnerAdminParams) error {
	_, err := q.db.Exec(ctx, setOwnerAdmin, arg.OwnerUuid, arg.IsAdmin)
	return err
}

const updateOwnerVenueLimit = `-- name: UpdateOwnerVenueLimit :exec
UPDATE venue_owners
SET venue_limit = $2, modified_at = now()
WHERE owner_uuid = $1
`

type UpdateOwnerVenueLimitParams struct {
	OwnerUuid  pgtype.UUID `json:"owner_uuid"`
	VenueLimit int32       `json:"venue_limit"`
}

func (q *Queries) UpdateOwnerVenueLimit(ctx context.Context, arg UpdateOwnerVenueLimitParams) error {
	_, err := q.db.Exec(ctx, updateOwnerVenueLimit, arg.OwnerUuid, arg.VenueLimit)
	return err
}
