// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (owner_uuid, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING token_uuid, owner_uuid, token_hash, expires_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.OwnerUuid, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenUuid,
		&i.OwnerUuid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationTokenByHash = `-- name: DeleteEmailVerificationTokenByHash :exec
DELETE FROM email_verification_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteEmailVerificationTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokenByHash, tokenHash)
	return err
}

const deleteEmailVerificationTokensByOwner = `-- name: DeleteEmailVerificationTokensByOwner :exec
DELETE FROM email_verification_tokens
WHERE owner_uuid = $1
`

func (q *Queries) DeleteEmailVerificationTokensByOwner(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByOwner, ownerUuid)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT token_uuid, owner_uuid, expires_at FROM email_verification_tokens
WHERE token_hash = $1
  AND expires_at > now()
`

type GetEmailVerificationTokenByHashRow struct {
	TokenUuid pgtype.UUID        `json:"token_uuid"`
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (GetEmailVerificationTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i GetEmailVerificationTokenByHashRow
	err := row.Scan(&i.TokenUuid, &i.OwnerUuid, &i.ExpiresAt)
	return i, err
}

const getLatestVerificationCreatedAtByOwner = `-- name: GetLatestVerificationCreatedAtByOwner :one
SELECT created_at FROM email_verification_tokens WHERE owner_uuid = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestVerificationCreatedAtByOwner(ctx context.Context, ownerUuid pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationCreatedAtByOwner, ownerUuid)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}
