// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    event_list_uuid,
    event_name,
    datetime,
    comment,
    duration_minutes,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING event_uuid, event_list_uuid, event_name, datetime, comment, duration_minutes, sort_order, created_at, modified_at
`

type CreateEventParams struct {
	EventListUuid   pgtype.UUID        `json:"event_list_uuid"`
	EventName       string             `json:"event_name"`
	Datetime        pgtype.Timestamptz `json:"datetime"`
	Comment         pgtype.Text        `json:"comment"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	SortOrder       int32              `json:"sort_order"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventListUuid,
		arg.EventName,
		arg.Datetime,
		arg.Comment,
		arg.DurationMinutes,
		arg.SortOrder,
	)
	var i Event
	err := row.Scan(
		&i.EventUuid,
		&i.EventListUuid,
		&i.EventName,
		&i.Datetime,
		&i.Comment,
		&i.DurationMinutes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE event_uuid = $1
  AND EXISTS (
    SELECT 1 FROM event_lists el
    INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
    WHERE el.event_list_uuid = events.event_list_uuid
      AND v.owner_uuid = $2
  )
`

type DeleteEventParams struct {
	EventUuid pgtype.UUID `json:"event_uuid"`
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.EventUuid, arg.OwnerUuid)
	return err
}

const getEventByIDAndOwner = `-- name: GetEventByIDAndOwner :one
SELECT e.event_uuid, e.event_list_uuid, e.event_name, e.datetime, e.comment, e.duration_minutes, e.sort_order, e.created_at, e.modified_at FROM events e
INNER JOIN event_lists el ON e.event_list_uuid = el.event_list_uuid
INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
WHERE e.event_uuid = $1 AND v.owner_uuid = $2
`

type GetEventByIDAndOwnerParams struct {
	EventUuid pgtype.UUID `json:"event_uuid"`
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) GetEventByIDAndOwner(ctx context.Context, arg GetEventByIDAndOwnerParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIDAndOwner, arg.EventUuid, arg.OwnerUuid)
	var i Event
	err := row.Scan(
		&i.EventUuid,
		&i.EventListUuid,
		&i.EventName,
		&i.Datetime,
		&i.Comment,
		&i.DurationMinutes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listEventsByEventListAndOwner = `-- name: ListEventsByEventListAndOwner :many
SELECT e.event_uuid, e.event_list_uuid, e.event_name, e.datetime, e.comment, e.duration_minutes, e.sort_order, e.created_at, e.modified_at FROM events e
INNER JOIN event_lists el ON e.event_list_uuid = el.event_list_uuid
INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
WHERE e.event_list_uuid = $1 AND v.owner_uuid = $2
ORDER BY e.sort_order ASC, e.datetime ASC
`

type ListEventsByEventListAndOwnerParams struct {
	EventListUuid pgtype.UUID `json:"event_list_uuid"`
	OwnerUuid     pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) ListEventsByEventListAndOwner(ctx context.Context, arg ListEventsByEventListAndOwnerParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByEventListAndOwner, arg.EventListUuid, arg.OwnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventUuid,
			&i.EventListUuid,
			&i.EventName,
			&i.Datetime,
			&i.Comment,
			&i.DurationMinutes,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    event_name = COALESCE($3, event_name),
    datetime = COALESCE($4, datetime),
    comment = $5,
    duration_minutes = $6,
    sort_order = COALESCE($7, sort_order)
WHERE event_uuid = $1
  AND EXISTS (
    SELECT 1 FROM event_lists el
    INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
    WHERE el.event_list_uuid = events.event_list_uuid
      AND v.owner_uuid = $2
  )
RETURNING event_uuid, event_list_uuid, event_name, datetime, comment, duration_minutes, sort_order, created_at, modified_at
`

type UpdateEventParams struct {
	EventUuid       pgtype.UUID        `json:"event_uuid"`
	OwnerUuid       pgtype.UUID        `json:"owner_uuid"`
	EventName       string             `json:"event_name"`
	Datetime        pgtype.Timestamptz `json:"datetime"`
	Comment         pgtype.Text        `json:"comment"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	SortOrder       int32              `json:"sort_order"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.EventUuid,
		arg.OwnerUuid,
		arg.EventName,
		arg.Datetime,
		arg.Comment,
		arg.DurationMinutes,
		arg.SortOrder,
	)
	var i Event
	err := row.Scan(
		&i.EventUuid,
		&i.EventListUuid,
		&i.EventName,
		&i.Datetime,
		&i.Comment,
		&i.DurationMinutes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
