// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_lists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEventList = `-- name: CreateEventList :one
INSERT INTO event_lists (
    venue_uuid,
    name,
    date,
    comment,
    visibility,
    private_link_token,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING event_list_uuid, venue_uuid, name, date, comment, visibility, private_link_token, sort_order, created_at, modified_at
`

type CreateEventListParams struct {
	VenueUuid        pgtype.UUID `json:"venue_uuid"`
	Name             string      `json:"name"`
	Date             pgtype.Date `json:"date"`
	Comment          pgtype.Text `json:"comment"`
	Visibility       string      `json:"visibility"`
	PrivateLinkToken pgtype.UUID `json:"private_link_token"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) CreateEventList(ctx context.Context, arg CreateEventListParams) (EventList, error) {
	row := q.db.QueryRow(ctx, createEventList,
		arg.VenueUuid,
		arg.Name,
		arg.Date,
		arg.Comment,
		arg.Visibility,
		arg.PrivateLinkToken,
		arg.SortOrder,
	)
	var i EventList
	err := row.Scan(
		&i.EventListUuid,
		&i.VenueUuid,
		&i.Name,
		&i.Date,
		&i.Comment,
		&i.Visibility,
		&i.PrivateLinkToken,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteEventList = `-- name: DeleteEventList :exec
DELETE FROM event_lists
WHERE event_list_uuid = $1
  AND EXISTS (
    SELECT 1 FROM venues v
    WHERE v.venue_uuid = event_lists.venue_uuid
      AND v.owner_uuid = $2
  )
`

type DeleteEventListParams struct {
	EventListUuid pgtype.UUID `json:"event_list_uuid"`
	OwnerUuid     pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) DeleteEventList(ctx context.Context, arg DeleteEventListParams) error {
	_, err := q.db.Exec(ctx, deleteEventList, arg.EventListUuid, arg.OwnerUuid)
	return err
}

const getEventListByIDAndOwner = `-- name: GetEventListByIDAndOwner :one
SELECT el.event_list_uuid, el.venue_uuid, el.name, el.date, el.comment, el.visibility, el.private_link_token, el.sort_order, el.created_at, el.modified_at FROM event_lists el
INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
WHERE el.event_list_uuid = $1 AND v.owner_uuid = $2
`

type GetEventListByIDAndOwnerParams struct {
	EventListUuid pgtype.UUID `json:"event_list_uuid"`
	OwnerUuid     pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) GetEventListByIDAndOwner(ctx context.Context, arg GetEventListByIDAndOwnerParams) (EventList, error) {
	row := q.db.QueryRow(ctx, getEventListByIDAndOwner, arg.EventListUuid, arg.OwnerUuid)
	var i EventList
	err := row.Scan(
		&i.EventListUuid,
		&i.VenueUuid,
		&i.Name,
		&i.Date,
		&i.Comment,
		&i.Visibility,
		&i.PrivateLinkToken,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listEventListsByVenueAndOwner = `-- name: ListEventListsByVenueAndOwner :many
SELECT el.event_list_uuid, el.venue_uuid, el.name, el.date, el.comment, el.visibility, el.private_link_token, el.sort_order, el.created_at, el.modified_at FROM event_lists el
INNER JOIN venues v ON el.venue_uuid = v.venue_uuid
WHERE el.venue_uuid = $1 AND v.owner_uuid = $2
ORDER BY el.sort_order ASC, el.created_at ASC
`

type ListEventListsByVenueAndOwnerParams struct {
	VenueUuid pgtype.UUID `json:"venue_uuid"`
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) ListEventListsByVenueAndOwner(ctx context.Context, arg ListEventListsByVenueAndOwnerParams) ([]EventList, error) {
	rows, err := q.db.Query(ctx, listEventListsByVenueAndOwner, arg.VenueUuid, arg.OwnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventList{}
	for rows.Next() {
		var i EventList
		if err := rows.Scan(
			&i.EventListUuid,
			&i.VenueUuid,
			&i.Name,
			&i.Date,
			&i.Comment,
			&i.Visibility,
			&i.PrivateLinkToken,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventList = `-- name: UpdateEventList :one
UPDATE event_lists
SET
    name = COALESCE($3, name),
    date = $4,
    comment = $5,
    visibility = COALESCE($6, visibility),
    private_link_token = $7,
    sort_order = COALESCE($8, sort_order)
WHERE event_list_uuid = $1
  AND EXISTS (
    SELECT 1 FROM venues v
    WHERE v.venue_uuid = event_lists.venue_uuid
      AND v.owner_uuid = $2
  )
RETURNING event_list_uuid, venue_uuid, name, date, comment, visibility, private_link_token, sort_order, created_at, modified_at
`

type UpdateEventListParams struct {
	EventListUuid    pgtype.UUID `json:"event_list_uuid"`
	OwnerUuid        pgtype.UUID `json:"owner_uuid"`
	Name             string      `json:"name"`
	Date             pgtype.Date `json:"date"`
	Comment          pgtype.Text `json:"comment"`
	Visibility       string      `json:"visibility"`
	PrivateLinkToken pgtype.UUID `json:"private_link_token"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) UpdateEventList(ctx context.Context, arg UpdateEventListParams) (EventList, error) {
	row := q.db.QueryRow(ctx, updateEventList,
		arg.EventListUuid,
		arg.OwnerUuid,
		arg.Name,
		arg.Date,
		arg.Comment,
		arg.Visibility,
		arg.PrivateLinkToken,
		arg.SortOrder,
	)
	var i EventList
	err := row.Scan(
		&i.EventListUuid,
		&i.VenueUuid,
		&i.Name,
		&i.Date,
		&i.Comment,
		&i.Visibility,
		&i.PrivateLinkToken,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
