// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geocode_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGeocodeCache = `-- name: GetGeocodeCache :one
SELECT normalized_address, lat, lng, display_name, created_at, updated_at
FROM geocode_cache
WHERE normalized_address = $1
`

func (q *Queries) GetGeocodeCache(ctx context.Context, normalizedAddress string) (GeocodeCache, error) {
	row := q.db.QueryRow(ctx, getGeocodeCache, normalizedAddress)
	var i GeocodeCache
	err := row.Scan(
		&i.NormalizedAddress,
		&i.Lat,
		&i.Lng,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenuesNeedingGeocode = `-- name: ListVenuesNeedingGeocode :many
SELECT venue_uuid, address
FROM venues
WHERE geolocation = '' AND address <> ''
ORDER BY created_at ASC
`

type ListVenuesNeedingGeocodeRow struct {
	VenueUuid pgtype.UUID `json:"venue_uuid"`
	Address   string      `json:"address"`
}

func (q *Queries) ListVenuesNeedingGeocode(ctx context.Context) ([]ListVenuesNeedingGeocodeRow, error) {
	rows, err := q.db.Query(ctx, listVenuesNeedingGeocode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVenuesNeedingGeocodeRow{}
	for rows.Next() {
		var i ListVenuesNeedingGeocodeRow
		if err := rows.Scan(&i.VenueUuid, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVenueGeolocation = `-- name: SetVenueGeolocation :exec
UPDATE venues
SET geolocation = $2, modified_at = now()
WHERE venue_uuid = $1
`

type SetVenueGeolocationParams struct {
	VenueUuid   pgtype.UUID `json:"venue_uuid"`
	Geolocation string      `json:"geolocation"`
}

func (q *Queries) SetVenueGeolocation(ctx context.Context, arg SetVenueGeolocationParams) error {
	_, err := q.db.Exec(ctx, setVenueGeolocation, arg.VenueUuid, arg.Geolocation)
	return err
}

const upsertGeocodeCache = `-- name: UpsertGeocodeCache :exec
INSERT INTO geocode_cache (
  normalized_address,
  lat,
  lng,
  display_name,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, now(), now()
)
ON CONFLICT (normalized_address) DO UPDATE
SET
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  display_name = EXCLUDED.display_name,
  updated_at = now()
`

type UpsertGeocodeCacheParams struct {
	NormalizedAddress string  `json:"normalized_address"`
	Lat               float64 `json:"lat"`
	Lng               float64 `json:"lng"`
	DisplayName       string  `json:"display_name"`
}

func (q *Queries) UpsertGeocodeCache(ctx context.Context, arg UpsertGeocodeCacheParams) error {
	_, err := q.db.Exec(ctx, upsertGeocodeCache,
		arg.NormalizedAddress,
		arg.Lat,
		arg.Lng,
		arg.DisplayName,
	)
	return err
}
