// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	TokenUuid pgtype.UUID        `json:"token_uuid"`
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	EventUuid       pgtype.UUID        `json:"event_uuid"`
	EventListUuid   pgtype.UUID        `json:"event_list_uuid"`
	EventName       string             `json:"event_name"`
	EventDate       pgtype.Date        `json:"event_date"`
	EventTime       pgtype.Time        `json:"event_time"`
	Comment         pgtype.Text        `json:"comment"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ModifiedAt      pgtype.Timestamptz `json:"modified_at"`
}

type EventList struct {
	EventListUuid    pgtype.UUID        `json:"event_list_uuid"`
	VenueUuid        pgtype.UUID        `json:"venue_uuid"`
	Name             string             `json:"name"`
	Date             pgtype.Date        `json:"date"`
	Comment          pgtype.Text        `json:"comment"`
	Visibility       string             `json:"visibility"`
	PrivateLinkToken pgtype.UUID        `json:"private_link_token"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}

type PasswordResetToken struct {
	TokenHash string             `json:"token_hash"`
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	RefreshTokenUuid    pgtype.UUID        `json:"refresh_token_uuid"`
	OwnerUuid           pgtype.UUID        `json:"owner_uuid"`
	TokenHash           string             `json:"token_hash"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenUuid pgtype.UUID        `json:"replaced_by_token_uuid"`
	UserAgent           pgtype.Text        `json:"user_agent"`
	IpAddress           pgtype.Text        `json:"ip_address"`
}

type Venue struct {
	VenueUuid        pgtype.UUID        `json:"venue_uuid"`
	OwnerUuid        pgtype.UUID        `json:"owner_uuid"`
	Name             string             `json:"name"`
	BannerImage      string             `json:"banner_image"`
	Address          string             `json:"address"`
	Geolocation      string             `json:"geolocation"`
	Comment          pgtype.Text        `json:"comment"`
	Timezone         string             `json:"timezone"`
	PrivateLinkToken pgtype.UUID        `json:"private_link_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}

type VenueOwner struct {
	OwnerUuid       pgtype.UUID        `json:"owner_uuid"`
	Name            string             `json:"name"`
	Mobile          string             `json:"mobile"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsAdmin         bool               `json:"is_admin"`
	IsDemo          bool               `json:"is_demo"`
	VenueLimit      int32              `json:"venue_limit"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ModifiedAt      pgtype.Timestamptz `json:"modified_at"`
}
