// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: owners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOwner = `-- name: CreateOwner :one
INSERT INTO venue_owners (name, email, mobile, password_hash, venue_limit)
VALUES ($1, $2, $3, $4, $5)
RETURNING owner_uuid, name, mobile, email, password_hash, is_admin, is_demo, venue_limit, email_verified_at, created_at, modified_at
`

type CreateOwnerParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	Mobile       string `json:"mobile"`
	PasswordHash string `json:"password_hash"`
	VenueLimit   int32  `json:"venue_limit"`
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (VenueOwner, error) {
	row := q.db.QueryRow(ctx, createOwner,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.PasswordHash,
		arg.VenueLimit,
	)
	var i VenueOwner
	err := row.Scan(
		&i.OwnerUuid,
		&i.Name,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDemo,
		&i.VenueLimit,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteOwner = `-- name: DeleteOwner :exec
DELETE FROM venue_owners
WHERE owner_uuid = $1
`

func (q *Queries) DeleteOwner(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOwner, ownerUuid)
	return err
}

const getOwnerByEmail = `-- name: GetOwnerByEmail :one
SELECT owner_uuid, name, mobile, email, password_hash, is_admin, is_demo, venue_limit, email_verified_at, created_at, modified_at FROM venue_owners
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetOwnerByEmail(ctx context.Context, lower string) (VenueOwner, error) {
	row := q.db.QueryRow(ctx, getOwnerByEmail, lower)
	var i VenueOwner
	err := row.Scan(
		&i.OwnerUuid,
		&i.Name,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDemo,
		&i.VenueLimit,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT owner_uuid, name, mobile, email, password_hash, is_admin, is_demo, venue_limit, email_verified_at, created_at, modified_at FROM venue_owners
WHERE owner_uuid = $1
`

func (q *Queries) GetOwnerByID(ctx context.Context, ownerUuid pgtype.UUID) (VenueOwner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, ownerUuid)
	var i VenueOwner
	err := row.Scan(
		&i.OwnerUuid,
		&i.Name,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDemo,
		&i.VenueLimit,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const setOwnerEmailVerified = `-- name: SetOwnerEmailVerified :exec
UPDATE venue_owners
SET email_verified_at = now(), modified_at = now()
WHERE owner_uuid = $1
`

func (q *Queries) SetOwnerEmailVerified(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setOwnerEmailVerified, ownerUuid)
	return err
}

const updateOwnerPassword = `-- name: UpdateOwnerPassword :exec
UPDATE venue_owners
SET password_hash = $1, modified_at = now()
WHERE owner_uuid = $2
`

type UpdateOwnerPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	OwnerUuid    pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) UpdateOwnerPassword(ctx context.Context, arg UpdateOwnerPasswordParams) error {
	_, err := q.db.Exec(ctx, updateOwnerPassword, arg.PasswordHash, arg.OwnerUuid)
	return err
}
