// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (token_hash, owner_uuid, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, owner_uuid, expires_at, created_at
`

type CreatePasswordResetTokenParams struct {
	TokenHash string             `json:"token_hash"`
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.TokenHash, arg.OwnerUuid, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.OwnerUuid,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordResetTokenByHash = `-- name: DeletePasswordResetTokenByHash :exec
DELETE FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) DeletePasswordResetTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokenByHash, tokenHash)
	return err
}

const deletePasswordResetTokensByOwner = `-- name: DeletePasswordResetTokensByOwner :exec
DELETE FROM password_reset_tokens
WHERE owner_uuid = $1
`

func (q *Queries) DeletePasswordResetTokensByOwner(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByOwner, ownerUuid)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT token_hash, owner_uuid, expires_at, created_at FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.OwnerUuid,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
