// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventListByToken = `-- name: GetEventListByToken :one
SELECT 
    el.event_list_uuid,
    el.venue_uuid,
    el.name,
    el.date,
    el.comment,
    el.visibility,
    el.private_link_token,
    el.sort_order,
    el.created_at,
    el.modified_at
FROM event_lists el
WHERE el.private_link_token = $1
`

func (q *Queries) GetEventListByToken(ctx context.Context, privateLinkToken pgtype.UUID) (EventList, error) {
	row := q.db.QueryRow(ctx, getEventListByToken, privateLinkToken)
	var i EventList
	err := row.Scan(
		&i.EventListUuid,
		&i.VenueUuid,
		&i.Name,
		&i.Date,
		&i.Comment,
		&i.Visibility,
		&i.PrivateLinkToken,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getPublicEventListsByVenue = `-- name: GetPublicEventListsByVenue :many
SELECT 
    event_list_uuid,
    venue_uuid,
    name,
    date,
    comment,
    visibility,
    private_link_token,
    sort_order,
    created_at,
    modified_at
FROM event_lists
WHERE venue_uuid = $1 AND visibility = 'public'
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) GetPublicEventListsByVenue(ctx context.Context, venueUuid pgtype.UUID) ([]EventList, error) {
	rows, err := q.db.Query(ctx, getPublicEventListsByVenue, venueUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventList{}
	for rows.Next() {
		var i EventList
		if err := rows.Scan(
			&i.EventListUuid,
			&i.VenueUuid,
			&i.Name,
			&i.Date,
			&i.Comment,
			&i.Visibility,
			&i.PrivateLinkToken,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenueByToken = `-- name: GetVenueByToken :one
SELECT 
    venue_uuid,
    name,
    banner_image,
    address,
    geolocation,
    comment,
    timezone,
    visibility,
    private_link_token,
    created_at,
    modified_at
FROM venues
WHERE private_link_token = $1
`

type GetVenueByTokenRow struct {
	VenueUuid        pgtype.UUID        `json:"venue_uuid"`
	Name             string             `json:"name"`
	BannerImage      string             `json:"banner_image"`
	Address          string             `json:"address"`
	Geolocation      string             `json:"geolocation"`
	Comment          pgtype.Text        `json:"comment"`
	Timezone         string             `json:"timezone"`
	Visibility       string             `json:"visibility"`
	PrivateLinkToken pgtype.UUID        `json:"private_link_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}

func (q *Queries) GetVenueByToken(ctx context.Context, privateLinkToken pgtype.UUID) (GetVenueByTokenRow, error) {
	row := q.db.QueryRow(ctx, getVenueByToken, privateLinkToken)
	var i GetVenueByTokenRow
	err := row.Scan(
		&i.VenueUuid,
		&i.Name,
		&i.BannerImage,
		&i.Address,
		&i.Geolocation,
		&i.Comment,
		&i.Timezone,
		&i.Visibility,
		&i.PrivateLinkToken,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getVenueWithEventListsByToken = `-- name: GetVenueWithEventListsByToken :many
SELECT 
    v.venue_uuid,
    v.name,
    v.banner_image,
    v.address,
    v.geolocation,
    v.comment,
    v.timezone,
    v.visibility,
    v.private_link_token,
    v.created_at,
    v.modified_at,
    el.event_list_uuid,
    el.name as event_list_name,
    el.date as event_list_date,
    el.comment as event_list_comment,
    el.visibility as event_list_visibility,
    el.private_link_token as event_list_private_link_token,
    el.sort_order as event_list_sort_order,
    el.created_at as event_list_created_at,
    el.modified_at as event_list_modified_at
FROM venues v
LEFT JOIN event_lists el ON el.venue_uuid = v.venue_uuid
WHERE v.private_link_token = $1
  AND (el.visibility = 'public' OR el.venue_uuid = v.venue_uuid)
ORDER BY el.sort_order ASC, el.created_at ASC
`

type GetVenueWithEventListsByTokenRow struct {
	VenueUuid                 pgtype.UUID        `json:"venue_uuid"`
	Name                      string             `json:"name"`
	BannerImage               string             `json:"banner_image"`
	Address                   string             `json:"address"`
	Geolocation               string             `json:"geolocation"`
	Comment                   pgtype.Text        `json:"comment"`
	Timezone                  string             `json:"timezone"`
	Visibility                string             `json:"visibility"`
	PrivateLinkToken          pgtype.UUID        `json:"private_link_token"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ModifiedAt                pgtype.Timestamptz `json:"modified_at"`
	EventListUuid             pgtype.UUID        `json:"event_list_uuid"`
	EventListName             pgtype.Text        `json:"event_list_name"`
	EventListDate             pgtype.Date        `json:"event_list_date"`
	EventListComment          pgtype.Text        `json:"event_list_comment"`
	EventListVisibility       pgtype.Text        `json:"event_list_visibility"`
	EventListPrivateLinkToken pgtype.UUID        `json:"event_list_private_link_token"`
	EventListSortOrder        pgtype.Int4        `json:"event_list_sort_order"`
	EventListCreatedAt        pgtype.Timestamptz `json:"event_list_created_at"`
	EventListModifiedAt       pgtype.Timestamptz `json:"event_list_modified_at"`
}

// Returns venue and all its event lists (public + private if venue token matches)
func (q *Queries) GetVenueWithEventListsByToken(ctx context.Context, privateLinkToken pgtype.UUID) ([]GetVenueWithEventListsByTokenRow, error) {
	rows, err := q.db.Query(ctx, getVenueWithEventListsByToken, privateLinkToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVenueWithEventListsByTokenRow{}
	for rows.Next() {
		var i GetVenueWithEventListsByTokenRow
		if err := rows.Scan(
			&i.VenueUuid,
			&i.Name,
			&i.BannerImage,
			&i.Address,
			&i.Geolocation,
			&i.Comment,
			&i.Timezone,
			&i.Visibility,
			&i.PrivateLinkToken,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.EventListUuid,
			&i.EventListName,
			&i.EventListDate,
			&i.EventListComment,
			&i.EventListVisibility,
			&i.EventListPrivateLinkToken,
			&i.EventListSortOrder,
			&i.EventListCreatedAt,
			&i.EventListModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicVenues = `-- name: ListPublicVenues :many
SELECT 
    venue_uuid,
    name,
    banner_image,
    address,
    geolocation,
    comment,
    timezone,
    visibility,
    private_link_token,
    created_at,
    modified_at
FROM venues
WHERE visibility = 'public'
  AND EXISTS (
    SELECT 1 FROM event_lists
    WHERE event_lists.venue_uuid = venues.venue_uuid
      AND event_lists.visibility = 'public'
  )
ORDER BY created_at DESC
`

type ListPublicVenuesRow struct {
	VenueUuid        pgtype.UUID        `json:"venue_uuid"`
	Name             string             `json:"name"`
	BannerImage      string             `json:"banner_image"`
	Address          string             `json:"address"`
	Geolocation      string             `json:"geolocation"`
	Comment          pgtype.Text        `json:"comment"`
	Timezone         string             `json:"timezone"`
	Visibility       string             `json:"visibility"`
	PrivateLinkToken pgtype.UUID        `json:"private_link_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}

func (q *Queries) ListPublicVenues(ctx context.Context) ([]ListPublicVenuesRow, error) {
	rows, err := q.db.Query(ctx, listPublicVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicVenuesRow{}
	for rows.Next() {
		var i ListPublicVenuesRow
		if err := rows.Scan(
			&i.VenueUuid,
			&i.Name,
			&i.BannerImage,
			&i.Address,
			&i.Geolocation,
			&i.Comment,
			&i.Timezone,
			&i.Visibility,
			&i.PrivateLinkToken,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicVenues = `-- name: SearchPublicVenues :many
SELECT DISTINCT
    v.venue_uuid,
    v.name,
    v.banner_image,
    v.address,
    v.geolocation,
    v.comment,
    v.timezone,
    v.visibility,
    v.private_link_token,
    v.created_at,
    v.modified_at
FROM venues v
WHERE v.visibility = 'public'
  AND EXISTS (
    SELECT 1 FROM event_lists el
    WHERE el.venue_uuid = v.venue_uuid
      AND el.visibility = 'public'
  )
  AND (
    v.name ILIKE '%' || $1 || '%'
    OR v.address ILIKE '%' || $1 || '%'
    OR v.comment ILIKE '%' || $1 || '%'
    OR EXISTS (
      SELECT 1 FROM event_lists el
      WHERE el.venue_uuid = v.venue_uuid
        AND (el.name ILIKE '%' || $1 || '%' OR el.comment ILIKE '%' || $1 || '%')
    )
    OR EXISTS (
      SELECT 1 FROM events e
      INNER JOIN event_lists el ON e.event_list_uuid = el.event_list_uuid
      WHERE el.venue_uuid = v.venue_uuid
        AND (e.event_name ILIKE '%' || $1 || '%' OR e.comment ILIKE '%' || $1 || '%')
    )
  )
ORDER BY v.created_at DESC
`

type SearchPublicVenuesRow struct {
	VenueUuid        pgtype.UUID        `json:"venue_uuid"`
	Name             string             `json:"name"`
	BannerImage      string             `json:"banner_image"`
	Address          string             `json:"address"`
	Geolocation      string             `json:"geolocation"`
	Comment          pgtype.Text        `json:"comment"`
	Timezone         string             `json:"timezone"`
	Visibility       string             `json:"visibility"`
	PrivateLinkToken pgtype.UUID        `json:"private_link_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}

func (q *Queries) SearchPublicVenues(ctx context.Context, dollar_1 pgtype.Text) ([]SearchPublicVenuesRow, error) {
	rows, err := q.db.Query(ctx, searchPublicVenues, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPublicVenuesRow{}
	for rows.Next() {
		var i SearchPublicVenuesRow
		if err := rows.Scan(
			&i.VenueUuid,
			&i.Name,
			&i.BannerImage,
			&i.Address,
			&i.Geolocation,
			&i.Comment,
			&i.Timezone,
			&i.Visibility,
			&i.PrivateLinkToken,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
