// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    owner_uuid,
    token_hash,
    expires_at,
    user_agent,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING refresh_token_uuid, owner_uuid, token_hash, issued_at, expires_at, revoked_at, replaced_by_token_uuid, user_agent, ip_address
`

type CreateRefreshTokenParams struct {
	OwnerUuid pgtype.UUID        `json:"owner_uuid"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.OwnerUuid,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshTokenUuid,
		&i.OwnerUuid,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenUuid,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT refresh_token_uuid, owner_uuid, token_hash, issued_at, expires_at, revoked_at, replaced_by_token_uuid, user_agent, ip_address FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshTokenUuid,
		&i.OwnerUuid,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenUuid,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const revokeAllTokensForOwner = `-- name: RevokeAllTokensForOwner :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE owner_uuid = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllTokensForOwner(ctx context.Context, ownerUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllTokensForOwner, ownerUuid)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE refresh_token_uuid = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, refreshTokenUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, refreshTokenUuid)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
SET replaced_by_token_uuid = $2
WHERE refresh_token_uuid = $1
`

type RotateRefreshTokenParams struct {
	RefreshTokenUuid    pgtype.UUID `json:"refresh_token_uuid"`
	ReplacedByTokenUuid pgtype.UUID `json:"replaced_by_token_uuid"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.RefreshTokenUuid, arg.ReplacedByTokenUuid)
	return err
}
