// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVenuesByOwner = `-- name: CountVenuesByOwner :one
SELECT COUNT(*) FROM venues
WHERE owner_uuid = $1
`

func (q *Queries) CountVenuesByOwner(ctx context.Context, ownerUuid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVenuesByOwner, ownerUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    owner_uuid,
    name,
    banner_image,
    address,
    geolocation,
    comment,
    timezone,
    private_link_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING venue_uuid, owner_uuid, name, banner_image, address, geolocation, comment, timezone, private_link_token, created_at, modified_at
`

type CreateVenueParams struct {
	OwnerUuid        pgtype.UUID `json:"owner_uuid"`
	Name             string      `json:"name"`
	BannerImage      string      `json:"banner_image"`
	Address          string      `json:"address"`
	Geolocation      string      `json:"geolocation"`
	Comment          pgtype.Text `json:"comment"`
	Timezone         string      `json:"timezone"`
	PrivateLinkToken pgtype.UUID `json:"private_link_token"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.OwnerUuid,
		arg.Name,
		arg.BannerImage,
		arg.Address,
		arg.Geolocation,
		arg.Comment,
		arg.Timezone,
		arg.PrivateLinkToken,
	)
	var i Venue
	err := row.Scan(
		&i.VenueUuid,
		&i.OwnerUuid,
		&i.Name,
		&i.BannerImage,
		&i.Address,
		&i.Geolocation,
		&i.Comment,
		&i.Timezone,
		&i.PrivateLinkToken,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues
WHERE venue_uuid = $1 AND owner_uuid = $2
`

type DeleteVenueParams struct {
	VenueUuid pgtype.UUID `json:"venue_uuid"`
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) DeleteVenue(ctx context.Context, arg DeleteVenueParams) error {
	_, err := q.db.Exec(ctx, deleteVenue, arg.VenueUuid, arg.OwnerUuid)
	return err
}

const getVenueByIDAndOwner = `-- name: GetVenueByIDAndOwner :one
SELECT venue_uuid, owner_uuid, name, banner_image, address, geolocation, comment, timezone, private_link_token, created_at, modified_at FROM venues
WHERE venue_uuid = $1 AND owner_uuid = $2
`

type GetVenueByIDAndOwnerParams struct {
	VenueUuid pgtype.UUID `json:"venue_uuid"`
	OwnerUuid pgtype.UUID `json:"owner_uuid"`
}

func (q *Queries) GetVenueByIDAndOwner(ctx context.Context, arg GetVenueByIDAndOwnerParams) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByIDAndOwner, arg.VenueUuid, arg.OwnerUuid)
	var i Venue
	err := row.Scan(
		&i.VenueUuid,
		&i.OwnerUuid,
		&i.Name,
		&i.BannerImage,
		&i.Address,
		&i.Geolocation,
		&i.Comment,
		&i.Timezone,
		&i.PrivateLinkToken,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listVenuesByOwner = `-- name: ListVenuesByOwner :many
SELECT venue_uuid, owner_uuid, name, banner_image, address, geolocation, comment, timezone, private_link_token, created_at, modified_at FROM venues
WHERE owner_uuid = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVenuesByOwner(ctx context.Context, ownerUuid pgtype.UUID) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByOwner, ownerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.VenueUuid,
			&i.OwnerUuid,
			&i.Name,
			&i.BannerImage,
			&i.Address,
			&i.Geolocation,
			&i.Comment,
			&i.Timezone,
			&i.PrivateLinkToken,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET
    name = COALESCE($3, name),
    banner_image = COALESCE($4, banner_image),
    address = COALESCE($5, address),
    geolocation = COALESCE($6, geolocation),
    comment = $7,
    timezone = COALESCE($8, timezone),
    private_link_token = $9
WHERE venue_uuid = $1 AND owner_uuid = $2
RETURNING venue_uuid, owner_uuid, name, banner_image, address, geolocation, comment, timezone, private_link_token, created_at, modified_at
`

type UpdateVenueParams struct {
	VenueUuid        pgtype.UUID `json:"venue_uuid"`
	OwnerUuid        pgtype.UUID `json:"owner_uuid"`
	Name             string      `json:"name"`
	BannerImage      string      `json:"banner_image"`
	Address          string      `json:"address"`
	Geolocation      string      `json:"geolocation"`
	Comment          pgtype.Text `json:"comment"`
	Timezone         string      `json:"timezone"`
	PrivateLinkToken pgtype.UUID `json:"private_link_token"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.VenueUuid,
		arg.OwnerUuid,
		arg.Name,
		arg.BannerImage,
		arg.Address,
		arg.Geolocation,
		arg.Comment,
		arg.Timezone,
		arg.PrivateLinkToken,
	)
	var i Venue
	err := row.Scan(
		&i.VenueUuid,
		&i.OwnerUuid,
		&i.Name,
		&i.BannerImage,
		&i.Address,
		&i.Geolocation,
		&i.Comment,
		&i.Timezone,
		&i.PrivateLinkToken,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
